class AppStrings {
  // Varsayılan dil
  static String language = 'tr';

  static final Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'home_title': 'Restoran Rezervasyon',
      'search_hint': 'Restoran veya yemek ara...',
      'reservations_title': 'Rezervasyonlarım',
      'reservations_cleanpage': 'Hemen Rezervasyon Yap',
      'reservations_lowtitle': 'Aktif Rezervasyon Yok',
      'tab_home': 'Restoranlar',
      'tab_reservations': 'Rezervasyonlar',
      'tab_profile': 'Profil',
      'tab_settings': 'Ayarlar',
      'settings_language': 'Dil',
      'settings_dark_mode': 'Koyu Mod',
      'settings_logout': 'Çıkış Yap',
      'settings_change_password': 'Şifremi Değiştir',
      'settings_delete_account': 'Hesabı Sil',
      'profile_reservations': 'Geçmiş Rezervasyonlarım',
      'profile_history': 'Geçmişi Sil',
      'category_all': 'Tümü',
      'category_kebab': 'Kebap',
      'category_burger': 'Burger',
      'category_pizza': 'Pizza',
      'category_fish': 'Balık',
      'general_header': 'GENEL',
      'account_header': 'HESAP',
      'dialog_select_language': 'Dil Seçin',
      'dialog_logout_content':
          'Uygulamadan çıkış yapmak istediğinize emin misiniz?',
      'dialog_delete_account_content':
          'Bu işlem geri alınamaz. Tüm rezervasyonlarınız ve verileriniz silinecektir. Emin misiniz?',
      'btn_cancel': 'İptal',
      'btn_delete': 'Sil',
      'msg_logout_success': 'Çıkış yapıldı.',
      'msg_delete_success': 'Hesabınız başarıyla silindi.',
      'msg_error_prefix': 'Hata: ',
      'version_text': 'Versiyon',
      'guest_user': 'Misafir Kullanıcı',
      'label_birth_date': 'Doğum Tarihi',
      'date_not_specified': 'Belirtilmemiş',
      'dialog_clear_history_title': 'Geçmişi Temizle',
      'dialog_clear_history_content':
          'Tüm geçmiş rezervasyon kayıtlarınız silinecek. Emin misiniz?',
      'btn_clear': 'Temizle',
      'msg_history_cleared': 'Geçmiş başarıyla temizlendi.',
      'err_loading': 'Yüklenemedi.',
      'no_past_reservations': 'Geçmiş rezervasyonunuz yok.',
      'label_person': 'Kişi',
      'dialog_cancel_reservation_title': 'Rezervasyonu İptal Et',
      'dialog_cancel_reservation_content':
          'Bu rezervasyonu silmek istediğinize emin misiniz?',
      'btn_yes': 'Evet',
      'btn_no': 'Hayır',
      'msg_reservation_cancelled': 'Rezervasyon iptal edildi.',
      'category_breakfast': 'Kahvaltı',
      'category_dessert': 'Tatlı',
      'category_pide': 'Pide',
      'category_doner': 'Döner',
      'category_asian': 'Uzak Doğu',
      'category_home_cooking': 'Ev Yemekleri',
      'category_street_food': 'Sokak Lezzetleri',

      'msg_no_data': 'Aradığınız kriterde restoran bulunamadı.',
      'msg_error': 'Hata oluştu.',
      'label_no_name': 'İsim Yok',
      'label_no_category': 'Kategori Yok',
      'label_no_desc': 'Açıklama yok',
      'label_reservation_date': 'Rezervasyon Tarihi',
      'label_select_date': 'Tarih Seçiniz',
      'label_party_size': 'Kişi Sayısı',
      'label_select_time': 'Saat Seçiniz',
      'label_available_slots': 'Uygun Saatler',
      'btn_create_reservation': 'Rezervasyonu Oluştur',
      'msg_reservation_success': 'Rezervasyon başarıyla oluşturuldu!',
      'msg_select_date_first': 'Lütfen önce tarih seçiniz.',
      'msg_no_slots': 'Bu tarihte uygun saat bulunamadı.',
      'msg_slot_error': 'Saatler yüklenemedi.',
      'status_full': 'DOLU',
      'status_past': 'Geçti',
      'status_selected': 'Seçildi',
      'text_available': 'boş',
      'title_register': 'Hesap Oluştur',
      'label_fullname': 'Ad Soyad',
      'label_dob': 'Doğum Tarihi (YYYY-MM-DD)',
      'label_email': 'E-posta',
      'label_password': 'Şifre',
      'label_enter_code': 'E-posta adresinize gelen\n6 haneli kodu girin:',
      'hint_dob': '1990-01-01',
      'btn_next': 'İlerle',
      'btn_complete': 'Tamamla',
      'msg_fill_all': 'Lütfen tüm alanları doldurun.',
      'msg_invalid_date_format': 'Tarihi tam giriniz (YYYY-MM-DD)',
      'msg_invalid_month': 'Geçersiz ay.',
      'msg_invalid_year': 'Yıl 1930 ile bugün arasında olmalıdır.',
      'msg_future_date': 'İleri bir tarih giremezsiniz.',
      'msg_invalid_day': 'Geçersiz tarih (Bu ay bu kadar gün çekmiyor).',
      'msg_date_error': 'Tarih formatı hatalı.',
      'msg_code_error': 'Girdiğiniz kod yanlış veya süresi dolmuş.',
      'msg_login_failed': 'Kod doğru ama giriş yapılamadı.',
      'title_app_name': 'Restorante',
      'btn_login': 'Giriş Yap',
      'btn_create_account': 'Hesap Oluştur',
      'label_forgot_password': 'Şifremi Unuttum',
      'label_remember_me': 'Beni Hatırla',
      'title_forgot_password': 'Şifre Sıfırlama',
      'label_enter_email': 'E-posta adresinizi girin:',
      'label_enter_code_short': 'Kodu girin:',
      'label_new_password': 'Yeni Şifre',
      'label_confirm_password': 'Şifreyi Tekrar Girin',
      'btn_send_code': 'Kod Gönder',
      'btn_verify': 'Doğrula',
      'btn_update_password': 'Şifreyi Güncelle',
      'msg_passwords_not_match': 'Şifreler uyuşmuyor!',
      'msg_password_updated': 'Şifre başarıyla güncellendi.',
      'msg_code_wrong': 'Kod yanlış.',
      'title_change_password': 'Güvenli Şifre Değiştirme',
      'msg_verify_identity':
          'Güvenliğiniz için önce mevcut giriş bilgilerinizi doğrulayın. Ardından mailinize bir kod göndereceğiz.',
      'label_current_password': 'Mevcut Şifreniz',
      'btn_verify_and_send': 'Doğrula ve Kod Gönder',
      'msg_code_sent': 'Doğrulama kodu mailinize gönderildi.',
      'msg_login_error': 'Giriş bilgileri hatalı, lütfen kontrol edin.',
      'msg_enter_code_sent_to': 'adresine gelen 6 haneli kodu giriniz.',
      'hint_code_placeholder': '______',
      'btn_confirm_code': 'Kodu Onayla',
      'btn_resend_code': 'Kodu Tekrar Gönder',
      'msg_resend_wait': 'Tekrar gönderildi. Lütfen bekleyin.',
      'msg_code_resent': 'Kod tekrar gönderildi.',
      'msg_identity_verified':
          'Kimliğiniz doğrulandı.\nYeni şifrenizi belirleyebilirsiniz.',
      'btn_change_password': 'Şifreyi Değiştir',
      'msg_password_changed_success':
          'Şifreniz başarıyla değiştirildi. Lütfen tekrar giriş yapın.',
      'tab_favorites': 'Favoriler',
      'title_favorites': 'Favori Restoranlarım',
      'msg_no_favorites': 'Henüz favori restoranınız yok.',
      'msg_added_fav': 'Favorilere eklendi.',
      'msg_removed_fav': 'Favorilerden çıkarıldı.',
    },
    'en': {
      'home_title': 'Restaurant Reservation',
      'search_hint': 'Search for restaurants or food...',
      'reservations_title': 'My Reservations',
      'reservations_cleanpage': 'Book Now',
      'reservations_lowtitle': 'No Active Reservations',
      'tab_home': 'Restaurants',
      'tab_reservations': 'Reservations',
      'tab_profile': 'Profile',
      'tab_settings': 'Settings',
      'settings_language': 'Language',
      'settings_dark_mode': 'Dark Mode',
      'settings_logout': 'Log Out',
      'settings_change_password': 'Change Password',
      'settings_delete_account': 'Delete Account',
      'profile_reservations': 'My past reservations',
      'profile_history': 'Delete History',
      'category_all': 'All',
      'category_kebab': 'Kebab',
      'category_burger': 'Burger',
      'category_pizza': 'Pizza',
      'category_fish': 'Fish',
      'general_header': 'GENERAL',
      'account_header': 'ACCOUNT',
      'dialog_select_language': 'Select Language',
      'dialog_logout_content': 'Are you sure you want to log out?',
      'dialog_delete_account_content':
          'This action cannot be undone. All your reservations and data will be deleted. Are you sure?',
      'btn_cancel': 'Cancel',
      'btn_delete': 'Delete',
      'msg_logout_success': 'Logged out successfully.',
      'msg_delete_success': 'Account deleted successfully.',
      'msg_error_prefix': 'Error: ',
      'version_text': 'Version',
      'guest_user': 'Guest User',
      'label_birth_date': 'Birth Date',
      'date_not_specified': 'Not specified',
      'dialog_clear_history_title': 'Clear History',
      'dialog_clear_history_content':
          'All past reservation records will be deleted. Are you sure?',
      'btn_clear': 'Clear',
      'msg_history_cleared': 'History cleared successfully.',
      'err_loading': 'Could not load.',
      'no_past_reservations': 'No past reservations.',
      'label_person': 'Person',
      'dialog_cancel_reservation_title': 'Cancel Reservation',
      'dialog_cancel_reservation_content':
          'Are you sure you want to delete this reservation?',
      'btn_yes': 'Yes',
      'btn_no': 'No',
      'msg_reservation_cancelled': 'Reservation cancelled.',
      'category_breakfast': 'Breakfast',
      'category_dessert': 'Dessert',
      'category_pide': 'Pide',
      'category_doner': 'Doner',
      'category_asian': 'Asian Cuisine',
      'category_home_cooking': 'Home Cooking',
      'category_street_food': 'Street Food',

      'msg_no_data': 'No restaurants found matching your criteria.',
      'msg_error': 'An error occurred.',
      'label_no_name': 'No Name',
      'label_no_category': 'No Category',
      'label_no_desc': 'No description',
      'label_reservation_date': 'Reservation Date',
      'label_select_date': 'Select Date',
      'label_party_size': 'Party Size',
      'label_select_time': 'Select Time',
      'label_available_slots': 'Available Slots',
      'btn_create_reservation': 'Create Reservation',
      'msg_reservation_success': 'Reservation created successfully!',
      'msg_select_date_first': 'Please select a date first.',
      'msg_no_slots': 'No available slots for this date.',
      'msg_slot_error': 'Could not load slots.',
      'status_full': 'FULL',
      'status_past': 'Past',
      'status_selected': 'Selected',
      'text_available': 'available',
      'title_register': 'Create Account',
      'label_fullname': 'Full Name',
      'label_dob': 'Date of Birth (YYYY-MM-DD)',
      'label_email': 'Email',
      'label_password': 'Password',
      'label_enter_code': 'Enter the 6-digit code\nsent to your email:',
      'hint_dob': '1990-01-01',
      'btn_next': 'Next',
      'btn_complete': 'Complete',
      'msg_fill_all': 'Please fill in all fields.',
      'msg_invalid_date_format': 'Enter full date (YYYY-MM-DD)',
      'msg_invalid_month': 'Invalid month.',
      'msg_invalid_year': 'Year must be between 1930 and today.',
      'msg_future_date': 'Cannot enter a future date.',
      'msg_invalid_day': 'Invalid date (Day does not exist in this month).',
      'msg_date_error': 'Date format error.',
      'msg_code_error': 'The code entered is incorrect or expired.',
      'msg_login_failed': 'Code verified but login failed.',
      'title_app_name': 'Restorante',
      'btn_login': 'Login',
      'btn_create_account': 'Create Account',
      'label_forgot_password': 'Forgot Password',
      'label_remember_me': 'Remember Me',
      'title_forgot_password': 'Reset Password',
      'label_enter_email': 'Enter your email address:',
      'label_enter_code_short': 'Enter code:',
      'label_new_password': 'New Password',
      'label_confirm_password': 'Confirm Password',
      'btn_send_code': 'Send Code',
      'btn_verify': 'Verify',
      'btn_update_password': 'Update Password',
      'msg_passwords_not_match': 'Passwords do not match!',
      'msg_password_updated': 'Password updated successfully.',
      'msg_code_wrong': 'Incorrect code.',
      'title_change_password': 'Secure Password Change',
      'msg_verify_identity':
          'For your security, verify your current login details first. We will then send a code to your email.',
      'label_current_password': 'Current Password',
      'btn_verify_and_send': 'Verify & Send Code',
      'msg_code_sent': 'Verification code sent to your email.',
      'msg_login_error': 'Incorrect login details, please check.',
      'msg_enter_code_sent_to': 'Enter the 6-digit code sent to',
      'hint_code_placeholder': '______',
      'btn_confirm_code': 'Confirm Code',
      'btn_resend_code': 'Resend Code',
      'msg_resend_wait': 'Resent. Please wait.',
      'msg_code_resent': 'Code resent.',
      'msg_identity_verified':
          'Identity verified.\nYou can set your new password.',
      'btn_change_password': 'Change Password',
      'msg_password_changed_success':
          'Password changed successfully. Please log in again.',
      'tab_favorites': 'Favorites',
      'title_favorites': 'My Favorite Restaurants',
      'msg_no_favorites': 'No favorite restaurants yet.',
      'msg_added_fav': 'Added to favorites.',
      'msg_removed_fav': 'Removed from favorites.',
    },
  };

  static String get(String key) {
    return _localizedValues[language]?[key] ?? key;
  }
}
